# Generated by Django 3.2.9 on 2021-11-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0008_rename_book_id_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summery',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
