# Generated by Django 3.2.9 on 2021-11-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0009_auto_20211112_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
